# Configuration for a plugin published to npm
[[plugins]]
package = "netlify-plugin-lighthouse"

  [plugins.inputs]
  output_path = "reports/lighthouse.html"

# Configuration for a local plugin
[[plugins]]
package = "/plugins/netlify-plugin-hello-world"